program = "main" "{" declarationList statementList "}".

declarationList = [declarationStat declarationList].
declarationStat = type ID (";" | "[" intNumber "]" ";").
type = "int" | "char" | "bool" | "double".

statementList = [statement statementList].
statement = ifStat | whileStat | readStat | writeStat | compoundStat | expressionStat | forStat | switchStat | breakStat | exitStat | continueStat | dowhileStat | repeatStat.
ifStat = "if" "(" expression ")" statement [ "else" statement].
whileStat = "while" "(" expression ")" statement.
readStat = "read" variable ";".
writeStat = "write" expression ";" .
compoundStat = "{" statementList "}".
expressionStat = expression ";" | ";".
forStat = "for" "(" expression ";" expression ";" expression ")" statement.
switchStat = "switch" "(" expression ")" "{" {"case" intNumber ":" statementList} ["default" ":" statementList] "}".
breakStat = "break" ";".
exitStat = "exit" "(" intNumber ")" ";".
continueStat = "continue" ";".
dowhileStat = "do" "{" statementList "}" "while" "(" expression ")" ";".
repeatStat = "repeat" "{" statementList "}" "until" "(" expression ")" ";".

expression = "#" variable "=" expression | valueExpr.
variable = simpleVariable ["++" | "--"] | ("++" | "--") simpleVariable.
simpleVariable = ID ["[" expression "]"].
valueExpr = simpleValue {("&&" | "||" | "XOR") simpleValue}.
simpleValue = odd additiveExpr | additiveExpr [(">" | "<" | ">=" | "<=" | "==" | "!=") additiveExpr].
additiveExpr = ["-"] term {("+"|"-") term}.
term = factor {("*"|"/"|"%") factor}.
factor = ["!"] ("(" expression ")"| variable | intNumber | doubleNumber | "true" | "false").
